'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.1
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SGL.BaseData.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property line1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("line1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MenuBarImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuBarImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property menuhigh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menuhigh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property menulight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menulight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property search1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tbtn_Counter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tbtn_Counter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tbtn_refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tbtn_refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tbtn_Restore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tbtn_Restore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 上() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("上", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 上条() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("上条", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 上查() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("上查", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 下() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("下", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 下推() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("下推", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 下条() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("下条", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 下查() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("下查", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 人员() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("人员", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 人员录入() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("人员录入", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 付款() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("付款", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 代码() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("代码", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 件号() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("件号", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 保存() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("保存", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 修改() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("修改", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 全清() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("全清", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 全选() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("全选", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 关联() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("关联", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 关闭() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("关闭", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 冲销() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("冲销", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 凭证() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("凭证", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 分解() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("分解", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 分配() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("分配", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 分配任务() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("分配任务", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 删行() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("删行", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 删除() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("删除", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 刷新() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("刷新", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 加锁() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("加锁", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 单据() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("单据", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 反分配() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("反分配", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 反分配1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("反分配1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 反核销() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("反核销", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 反确认() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("反确认", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 变更() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("变更", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 合并() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("合并", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 启用() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("启用", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 固定资产() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("固定资产", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 固定资产变动() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("固定资产变动", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 图片() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("图片", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 图表() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("图表", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 复制() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("复制", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 多级审核() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("多级审核", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 实仓() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("实仓", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 实仓1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("实仓1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 审核() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("审核", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 容量() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("容量", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 密码() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("密码", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 导出() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("导出", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 导出excel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("导出excel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 平衡() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("平衡", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 库位() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("库位", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 库存盘点() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("库存盘点", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 库龄() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("库龄", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 待检() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("待检", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 成本() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("成本", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 打印() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("打印", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 打印1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("打印1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 打印设置() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("打印设置", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 打印设置1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("打印设置1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 打印预览() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("打印预览", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 打开() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("打开", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 批量修改() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("批量修改", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 批量过帐() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("批量过帐", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 拆单() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("拆单", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 排序() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("排序", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 撤消() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("撤消", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 撤销() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("撤销", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 新增() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("新增", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 日期() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("日期", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 末条() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("末条", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 条码() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("条码", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 查找() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("查找", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 查找人员() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("查找人员", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 查看() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("查看", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 查询() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("查询", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 查询2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("查询2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 核销() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("核销", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 格式() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("格式", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 添行() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("添行", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 清单() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("清单", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 物料() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("物料", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 物料全部() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("物料全部", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 现金() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("现金", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 百分符() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("百分符", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 确认() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("确认", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 禁用() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("禁用", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 移入() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("移入", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 移出() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("移出", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 移库() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("移库", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 立体() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("立体", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 红字() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("红字", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 维护() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("维护", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 自动() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("自动", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 虚仓() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("虚仓", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 解锁() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("解锁", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 计算() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("计算", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 试算平衡() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("试算平衡", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 过滤() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("过滤", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 退出() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("退出", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 选入() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("选入", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 选出() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("选出", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 选项() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("选项", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 钩稽() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("钩稽", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 附件() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("附件", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 页距设置() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("页距设置", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 首条() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("首条", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 驳回() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("驳回", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
